import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);
const base=process.env.ROMPA_TEST_URL||'http://127.0.0.1:4173';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1});
const page=await context.newPage();const failures=[];
page.on('pageerror',error=>failures.push(error.message));
page.on('response',r=>{if(r.status()>=400)failures.push(`${r.status()}: ${r.url()}`);});
await mkdir(new URL('../test-artifacts/',import.meta.url),{recursive:true});
const shot=name=>page.screenshot({path:fileURLToPath(new URL(`../test-artifacts/${name}.png`,import.meta.url)),fullPage:true});
const current=()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('rompa.assessment.v1')));
const next=()=>page.getByRole('button',{name:'Continuar',exact:true}).click();
// Inputs são visualmente ocultos para manter a seleção nativa acessível;
// clicar no label percorre o mesmo fluxo que o usuário.
const choose=value=>page.locator(`label.option:has(input[value="${value}"])`).click();
const fill=value=>page.locator('#answer').fill(value);
const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow em ${(await current()).screen}`);
try{
  await page.goto(`${base}/teste/?utm_source=qa&utm_campaign=teste-mesa`);
  await page.getByRole('button',{name:'Começar meu teste'}).waitFor();await noOverflow();await shot('mobile-landing');
  await page.getByRole('button',{name:'Começar meu teste'}).click();
  await page.locator('#storage-consent').check();
  await page.getByRole('button',{name:'Entendi. Vamos começar'}).click();
  await page.getByRole('button',{name:'Localizar minha situação'}).click();
  await next();assert.ok(await page.locator('#error').textContent());
  await choose('PROJETOS_OBJETIVOS');await next();assert.equal(await page.locator('.option').count(),6);
  await choose('P01');await next();await page.getByRole('button',{name:'Contar o que acontece'}).click();
  await fill('Começo projetos e depois abandono. <img src=x onerror=alert(1)>');await next();
  await page.getByRole('button',{name:'Continuar observando'}).click();await choose('FREQUENTE');await next();
  await page.reload();assert.equal((await current()).screen,'Q05');assert.equal((await current()).session.utm_source,'qa');
  await page.getByRole('button',{name:'← Voltar',exact:true}).click();assert.equal(await page.locator('input:checked').inputValue(),'FREQUENTE');await next();
  await choose('ANOS');await next();await page.getByRole('button',{name:'Observar meu ciclo'}).click();
  for(const v of ['CRITICA','PRESSAO','CANSACO'])await choose(v);
  assert.ok(await page.locator('input[value="FRUSTRACAO"]').isDisabled());await choose('CANSACO');await choose('FRUSTRACAO');await noOverflow();await shot('mobile-question');await next();
  await choose('SIM');await next();assert.equal((await current()).screen,'Q08');await choose('TENSAO');await next();
  await page.getByRole('button',{name:'← Voltar',exact:true}).click();await page.getByRole('button',{name:'← Voltar',exact:true}).click();
  await choose('NAO');await next();assert.equal((await current()).screen,'Q09');assert.equal((await current()).answers.sinais_percebidos,undefined);
  await choose('AFTER');await next();await next();await choose('RARAMENTE');await next();await fill('Deixo o projeto de lado.');await next();
  await choose('ABANDONO');await choose('RECOMECO');await next();await page.getByRole('button',{name:'Escolher meu foco'}).click();
  await fill('Concluir um projeto.');await next();await fill('Terminar o que começo.');await next();await choose('LIVROS');await next();
  await page.getByRole('button',{name:'Organizar meu perfil'}).click();await page.getByRole('button',{name:'Liberar meu perfil'}).waitFor();
  await page.getByRole('button',{name:'← Voltar',exact:true}).click();assert.equal((await current()).screen,'complete');await page.getByRole('button',{name:'Organizar meu perfil'}).click();await page.getByRole('button',{name:'Liberar meu perfil'}).waitFor();
  await page.locator('#name').fill('Teste');await page.locator('#phone').fill('+55 11 99999-9999');
  assert.equal(await page.locator('[name="marketing_consent"]').isChecked(),false);
  await page.getByRole('button',{name:'Liberar meu perfil'}).click();assert.match(await page.locator('#error').textContent(),/necessário/);
  await page.locator('[name="privacy_acceptance"]').check();await page.getByRole('button',{name:'Liberar meu perfil'}).click();
  await page.locator('.profile-hero').waitFor();await noOverflow();assert.equal(await page.locator('.voice img').count(),0);assert.ok((await page.locator('.voice').textContent()).includes('<img src=x'));
  assert.equal((await current()).assessment.user_id,(await current()).user.id);assert.equal(await page.locator('#checkout').getAttribute('href'),'https://pay.hotmart.com/D107689179A');
  await page.getByRole('button',{name:'Sim, muito bem',exact:true}).click();assert.equal((await current()).feedback,0);
  await page.locator('.interruption').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await shot('mobile-profile');
  await page.reload();assert.equal((await current()).screen,'profile');await noOverflow();
  await page.setViewportSize({width:1440,height:1000});await noOverflow();await shot('desktop-profile');
  const second=await context.newPage();await second.goto(`${base}/teste/`);await second.getByRole('button',{name:'Começar meu teste'}).waitFor();
  const other=await second.evaluate(()=>JSON.parse(sessionStorage.getItem('rompa.assessment.v1')));assert.notEqual(other.session.id,(await current()).session.id);assert.deepEqual(other.answers,{});await second.close();
  const events=(await current()).events.map(e=>e.event_name);for(const event of ['test_start','localizar_completed','descrever_completed','investigar_completed','priorizar_completed','test_completed','lead_submitted','profile_generated','profile_viewed','interruption_window_viewed','profile_feedback'])assert.ok(events.includes(event),event);
  page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Apagar respostas e recomeçar'}).click();await page.getByRole('button',{name:'Começar meu teste'}).waitFor();assert.equal((await current()).user,null);assert.deepEqual((await current()).answers,{});
  await page.setViewportSize({width:320,height:740});await noOverflow();
  assert.deepEqual(failures,[]);console.log('Browser QA passed: full journey, branching, limits, validation, recovery, XSS, feedback, session isolation, 320/390/1440px.');
}finally{await browser.close();}
